//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouse.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryEntity
    {
        public int InventoryID { get; set; }
        public int Quantity { get; set; }
        public int ProductID { get; set; }
    
        public virtual ProductEntity Product { get; set; }
    }
}
